#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

files=$(git --no-pager diff --staged --name-only --diff-filter=ACMR -- "*.js" "*.jsx")

[ -z "$files" ] && exit 0

# Prettify all selected files
echo "$files" | xargs ./node_modules/.bin/prettier --write

# Lint all selected files
echo "$files" | xargs ./node_modules/.bin/eslint --quiet

# Add back the modified/prettified files to staging
echo "$files" | xargs git add

exit 0